from .autorserializer import AutorSerializer
from .categoriaserializer import CategoriaSerializer
from .editoraserializer import EditoraSerializer
from .livrodetailserializer import LivroDetailSerializer
from .livroserializer import LivroSerializer